# services:
#   rabbit-1:
#     image: rabbitmq:3-management
#     container_name: rabbit-1
#     hostname: rabbit-1
#     networks:
#       # - rabbitnet
#       # net1:
#       #   ipv4_address: 172.21.0.2
#       # net2:
#       # net3:
#       net_rabbit:
#         ipv4_address: 172.25.0.2
#     ports:
#       - "15672:15672"
#       - "5672:5672"
#     environment:
#       RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
#       RABBITMQ_NODENAME: rabbit@rabbit-1
#       RABBITMQ_DEFAULT_USER: admin
#       RABBITMQ_DEFAULT_PASS: admin
#     volumes:
#       - rabbit_1:/var/lib/rabbitmq
#       - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#     # extra_hosts:
#     #   - "rabbit-2:172.22.0.2"
#     #   - "rabbit-3:172.23.0.2"

#   rabbit-2:
#     image: rabbitmq:3-management
#     container_name: rabbit-2
#     hostname: rabbit-2
#     networks:
#       # - rabbitnet
#       # net1:
#       # net2:
#       #   ipv4_address: 172.22.0.2
#       # net3:
#       net_rabbit:
#         ipv4_address: 172.25.0.3
#     ports:
#       - "15673:15672"
#       - "5673:5672"
#     environment:
#       RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
#       RABBITMQ_NODENAME: rabbit@rabbit-2
#       RABBITMQ_DEFAULT_USER: admin
#       RABBITMQ_DEFAULT_PASS: admin
#     volumes:
#       - rabbit_2:/var/lib/rabbitmq
#       - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#     # extra_hosts:
#     #   - "rabbit-1:172.21.0.2"
#     #   - "rabbit-3:172.23.0.2"

#   rabbit-3:
#     image: rabbitmq:3-management
#     container_name: rabbit-3
#     hostname: rabbit-3
#     networks:
#       # - rabbitnet
#       # net1:
#       # net2:
#       # net3:
#       #   ipv4_address: 172.23.0.2
#       net_rabbit:
#         ipv4_address: 172.25.0.4
#     ports:
#       - "15674:15672"
#       - "5674:5672"
#     environment:
#       RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
#       RABBITMQ_NODENAME: rabbit@rabbit-3
#       RABBITMQ_DEFAULT_USER: admin
#       RABBITMQ_DEFAULT_PASS: admin
#     volumes:
#       - rabbit_3:/var/lib/rabbitmq
#       - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#     # extra_hosts:
#     #   - "rabbit-1:172.21.0.2"
#     #   - "rabbit-2:172.22.0.2"

# volumes:
#   rabbit_1:
#   rabbit_2:
#   rabbit_3:

# networks:
#   # rabbitnet:
#   #   driver: bridge
#   # net1:
#   #   driver: bridge
#   #   ipam:
#   #     config:
#   #       - subnet: 172.21.0.0/24
#   # net2:
#   #   driver: bridge
#   #   ipam:
#   #     config:
#   #       - subnet: 172.22.0.0/24
#   # net3:
#   #   driver: bridge
#   #   ipam:
#   #     config:
#   #       - subnet: 172.23.0.0/24
#   # net-comum:
#   #   driver: bridge
#   #   ipam:
#   #     config:
#   #       - subnet: 172.24.0.0/24

#   net_rabbit:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.25.0.0/24

services:
  rabbit-kev:
    image: rabbitmq:3-management
    container_name: rabbit-kev
    hostname: rabbit-kev
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25672:25672"
      - "4369:4369"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_NODENAME: rabbit@rabbit-kev
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_kev:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    extra_hosts:
      - "rabbit-adr:192.168.255.102"
      - "rabbit-adr:192.168.255.106"

volumes:
  rabbit_kev: