services:
  rabbit-1:
    image: rabbitmq:3-management
    container_name: rabbit-1
    hostname: r1
    networks:
      - rabbitnet
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_NODENAME: rabbit@r1
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_1:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-2:
    image: rabbitmq:3-management
    container_name: rabbit-2
    hostname: r2
    networks:
      - rabbitnet
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@r2
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_2:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-3:
    image: rabbitmq:3-management
    container_name: rabbit-3
    hostname: r3
    networks:
      - rabbitnet
    ports:
      - "15674:15672"
      - "5674:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@r3
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_3:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  rabbit_1:
  rabbit_2:
  rabbit_3:

networks:
  rabbitnet:
    driver: bridge