services:
  rabbit-kev:
    image: rabbitmq:3-management
    container_name: rabbit-kev
    hostname: rabbit-kev
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25672:25672"
      - "4369:4369"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_NODENAME: rabbit@rabbit-kev
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_kev:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    extra_hosts:
      - "rabbit-adr:192.168.255.102"
      - "rabbit-adr:192.168.255.106"

volumes:
  rabbit_kev: